# Generated by Django 3.1 on 2020-09-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Pincode',
            new_name='Phone',
        ),
    ]
