# Generated by Django 3.1 on 2020-09-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtest', '0006_auto_20200912_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='Phone',
            field=models.BigIntegerField(),
        ),
    ]
